unplugin/unplugin-vue-components

src/context.ts

fix: windows build

---

example/package.json
example/vite.config.ts
package.json
pnpm-lock.yaml
src/context.ts
src/utils.ts

https://github.com/vitejs/vite/commit/0318c64cc3efe970a5cd3ef6624fe3625af06012

fix: alias in latest vite

---

src/context.ts
src/utils.ts

Closes #19
Saved you some time :)
Tested on both Mac and Win

fix: fix paths in Windows

---

src/context.ts
src/types.ts
src/utils.ts

fix: separate glob for watching

---

src/resolvers/index.ts
src/resolvers/vuetify.ts

Dear @antfu, I've created a resolver for Vuetify component. 
Please kindly review. For implementation example you can see here: https://github.com/martinussuherman/demo-vue-oidc
Regards,
Martinus

feat: add vuetify resolver

---

examples/vue3/src/main.ts
src/resolvers/vant.ts

support import vant component'style file on demand.

feat: modify vant resolver

---

README.md

chore: add warn about include `components.d.ts`

---

src/resolvers/antdv.ts

fix: update antdv version, fix style lost

---

src/resolvers/antdv.ts

feat: support antdv css style on demand

---

src/resolvers/antdv.ts

chore: remove duplicate code

---

package.json
pnpm-lock.yaml
src/resolvers/element-plus.ts
src/utils.ts

support min version 1.0.2 and above,  add option called lagency to support 1.0.2

feat: support element-plus v1.1

---

src/core/resolvers/element-plus.ts

The return values of `compareVersions` is `[1, 0, -1]`, and `Boolean(-1) === true` in js.

fix: compare version

---

src/core/resolvers/antdv.ts

add cjs option to  resolve noe enviroment build error

fix(antdv): add cjs options, close #202

---

src/core/declaration.ts

fix: remove or delete update component.d.ts

---

README.md
src/core/resolvers/arco.ts

feat(arco): add arco design vue resolver

---

src/core/resolvers/headless-ui.ts

feat(headless-ui): add prefix option to headless ui resolver

---

README.md

add tdesign to readme resolvers

docs: add tdesign to readme resolvers

---

src/core/resolvers/arco.ts

Add support for GridItem.
Thank you~

feat(arco): add new component support

---

src/core/resolvers/tdesign.ts

fixed : use t-radio-group and t-radio-button component can not resolve

fix(tdesign): t-radio-group t-radio-button

---

src/core/resolvers/antdv.ts

Add support for TimeRangePicker.
Thank you~

fix(antdv): set a-time-range-picker styleDir, close #286

---

src/core/resolvers/element-plus.ts

add excludeReg parameter for element-plus resolver，then other component can use El prefix
#295

feat(element-plus): add exclude option (#296)

---

src/core/resolvers/headless-ui.ts

fix(headless-ui): fix prefix option not found bug

---

src/core/context.ts

solve the issue 👉 [Can't detect new added component in windows 11 #281](https://github.com/antfu/unplugin-vue-components/issues/281)

fix(normalizePath): windows to POSIX

---

src/core/resolvers/tdesign.ts

sorry @antfu , just realised we forgot to provide configuration for `icon` & `head-menu`  :)

fix(tdesign): resolver

---

src/core/resolvers/arco.ts

I write a compent name autohide then ... error , do this can fix

fix(acro): component name matcher

---

src/core/resolvers/headless-ui.ts

[headlessui v1.5.0](https://github.com/tailwindlabs/headlessui/releases/tag/%40headlessui%2Fvue%40v1.5.0) introduced a new combobox component

feat(headlessui): add combox components

---

src/core/declaration.ts

fix: extend type GlobalComponents in "@vue/runtime-core"

---

src/core/resolvers/arco.ts

After upgrading to 0.19.x, Arco Design's resolver was broken.
I tried to modify it, and found that it works.

fix(arco): resolver

---

src/core/resolvers/arco.ts

Resolve the problem that the Arco Design's resolver miss component `DropdownButton`

fix(arco): upgrade resolver

---

src/core/resolvers/tdesign.ts

TDesign adds `color-picker`、`text`、`collapse`、`time-range-picker-panel` and `date-range-picker-panel` resolve rules

fix(tdesign): upgrade resolver

---

src/core/resolvers/vueuse.ts

the latest version of vueuse changes the location of the index file, this change aims to adapt the resolver to the latest version of vueuse.

fix: compactible with VueUse v8

---

src/core/resolvers/idux.ts

fix https://github.com/IDuxFE/idux/issues/902

fix(idux): update resolver

---

src/core/resolvers/element-plus.ts

refactor(resolver): update element plus default version

---

README.md

Add missing importPathTransform and allowOverrides to configuration section.
Also, add an example for importPathTransform

docs: update configuration and examples

---

src/core/resolvers/arco.ts

feat(arco): add new component support and fix skeleton problem

---

README.md
src/core/resolvers/devui.ts

feat(devui): refactor devui resolver

---

src/core/options.ts

fix: compatible with CJS

---

src/core/resolvers/tdesign.ts

Add resolver color-picker for tdesign

fix(tdesign): add resolver color-picker

---

src/core/resolvers/tdesign.ts

chore: lint

---

src/core/resolvers/element-ui.ts

feat(element-ui): add exclude option

---

src/core/resolvers/idux.ts

feat(idux): add scope supports

---

src/core/resolvers/varlet-ui.ts

1. Support automatic import of VarletUI's  methods
- Snackbar
- Picker
- ActionSheet
- Dialog
- Locale
- StyleProvider` 
2.Support `unplugin-auto-import`

feat(varlet-ui): support unplugin-auto-import

---

src/core/transforms/directive/vue2.ts

fix: get render start in vue 2 directive

---

src/core/utils.ts
test/utils.test.ts

feat: remove special char in namespace

---

src/core/utils.ts

fix: kebab namespace cannot invert to camel correctly

---

src/core/resolvers/varlet-ui.ts

Support loading-bar component for varlet ui

feat(varlet-ui): support loading-bar

---

src/core/resolvers/tdesign.ts

- Support pagination-mini component for TDesign
- https://github.com/Tencent/tdesign-vue-next/issues/2226

fix(tdesign): add pagination-mini resolver

---

src/core/declaration.ts

same question: https://github.com/antfu/unplugin-auto-import/pull/308

fix: generator dts (no such file or directory)

---

package.json

feat: add types fields

---

src/core/resolvers/devui.ts

调整DevUiresolver，解决引入D-Row、D-Col错误的问题
fix #579
https://github.com/antfu/unplugin-vue-components/issues/579
没有

fix(resolver): repaired import row and col in devui_resolver

---

README.md

docs: improve options section

---

README.md

We've been getting lots of support questions from people using unplugin-vue-components, our own build plugins use a map which is more efficient and avoids matching components that don't exist in the library.

chore(readme): link to vuetify plugins

---

src/core/context.ts

chore: debug declaration typo

---

src/core/resolvers/devui.ts

fix(resolver/devui): fix components not found

---

src/core/resolvers/antdv.ts

support antdv 4.0  add some component ('FloatButton', 'FloatButtonGroup', 'Qrcode', 'Watermark', 'Segmented', 'Tour') 
#631

feat: support antdv4

---

src/core/resolvers/idux.ts

feat(idux): add new components

---

src/core/resolvers/element-plus.ts

Added `nightly` option to support nightly releases.

feat(element-plus): support nightly option

---

README.md

Include license link in readme footer.
NA

docs: include license link in readme

---

src/core/transformer.ts

same questions: https://github.com/unplugin/unplugin-auto-import/pull/384
https://github.com/unplugin/unplugin-vue-components/issues/687

fix: generate sourcemap with hires (#687)

---

src/core/resolvers/antdv.ts

This component has been available since version 4.0.7  
https://www.antdv.com/components/flex-cn

feat(antdv): Add new component

---

src/core/resolvers/bootstrap-vue.ts

feat: deprecate bvn resolver

---

package.json
pnpm-lock.yaml
src/core/resolvers/veui.ts
src/core/utils.ts

I ran `pnpx ihimnm`, and found this

deps: replace resolve with mlly

---

src/core/resolvers/ionic.ts

sycn with nuxt/ionic based on:
https://github.com/unplugin/unplugin-vue-components/pull/750#issuecomment-2495440953

feat: sync ionic 8.4

---

src/core/declaration.ts

fix: extractImports supported CRLF files

---

README.md

This PR adds documentation about the default values of the types configuration.
closed: #855

docs: clarify `types` configuration

---

README.md

docs: add TDesign's own auto-import resolver

---

README.md
package.json
pnpm-lock.yaml
src/rolldown.ts

Support [`rolldown`](https://github.com/rolldown/rolldown) export to use this plugin with [`tsdown`](https://github.com/rolldown/tsdown), [`rolldown`](https://github.com/rolldown/rolldown) or [`rolldown-vite`](https://github.com/vitejs/rolldown-vite)
Resolves: #873
I'm not sure if `rolldown` should be added as a dev dependency. Could I request some feedback on this?

feat: add support for `rolldown`
