README.md
src/context.ts
src/index.ts
src/types.ts
src/utils.ts
test/fixture/src/App.vue
test/fixture/src/components/Recursive.vue
test/fixture/src/components/book/index.vue
test/fixture/src/components/global/avatar.vue
test/fixture/src/components/ui/button.vue
test/fixture/src/components/ui/nested/checkbox.vue
test/fixture/src/index.css
test/fixture/vite.config.ts

Hello there,
so ive created a smaller Pull Request that basically implements some Features that i had in my own `vite-autoloader`.
Due to it not beeing in Typescript ive converted all Features that were missing now over to this Plugin!
Features:
1.  Allow Folder Names ( boolean )
This is just a simple Idea, if you for example got the following Folder Structure:
```
src/components
book.vue
ui
button.vue
layout
content.vue
transition
fade.vue
```
Components within these Subfolders would be generated like the following:
`book.vue`, `uiButton.vue` , `layoutContent.vue`, `transitionFade.vue`
This allows Users to have Componentnames based on their Foldestructure.
2. Namespacing ( array with strings )
An Additional Feature to the first one: the user can allow specific Foldernames to be ignored …

feat: directory namespaces support

---

README.md

It seems there is a typo in the documentation to use the custom resolver. I have to change `customResolvers ` to `customComponentResolvers` to make it works

chore: typo customResolvers to customComponentResolvers

---

src/resolvers/headlessUi.ts
src/resolvers/index.ts

Hi people!
I created a resolver for headlessUi
https://github.com/tailwindlabs/headlessui
The problem with headlessUi is, that its components are not prefixed and therefore a simple regex or startsWith cannot be used to identify them. As you can see the solution for this was having a string array with all component names and checking if the resolved component is included. Having a hardcoded array of names is not an optimal solution.
The headlessUi package exports all the components. A dynamic solution could look something like this:
`import * as components from '@headlessui/vue'`
`const components = Object.keys(components)`
The downside to this is, that you have to import the whole package.
I do not know which solution is better, so feedback is welcome.
PS: This is my first contribution …

feat(resolver): add headlessUi resolver

---

src/context.ts
src/index.ts

In windows, if you add components dir to watchlist, the watcher will not works under components dir.
Also, Vite is defaulted to watching everything under root dir, so I think we don't need to add components dir manually.
close #86 
close https://github.com/antfu/vitesse/issues/149

fix: watcher not works under components dir in windows

---

src/resolvers/antdv.ts

-  fix `UploadDragger` import styles fail
`Upload` components has a `UploadDragger` exports, but `styleDir` is exists in the `upload` folder.
- [ant-design-vue](https://2x.antdv.com/components/upload#components-upload-demo-drag)
- [pr with ant-design-vue for exports UploadDragger](https://github.com/vueComponent/ant-design-vue/pull/4334)

fix(antdv): fix `UploadDragger` import styles fail

---

src/resolvers/antdv.ts

AntdDesignVue`s icons is a alone package, so we need to import icons from @ant-design/icons-vue.
[click here for detail](https://2x.antdv.com/components/icon)

feat(antdv): add antdv icons resolve options.

---

README.md

Minor suggestion to clarify the readme, re code splitting.

docs: clarify code splitting behaviour in README

---

src/core/resolvers/veui.ts

Support component level style/config/locale injection. Shares the same options with `veui-loader`.
See https://veui.dev/en-US/getting-started/veui-loader#options.

feat: add side-effects support for VeuiResolver

---

src/core/resolvers/antdv.ts

Hey, sometimes I need to exclude components that I don't need to automatically import because I registered a component globally with the same name as the component library, and if I don't exclude that component, the auto-imported component will overwrite the components that I registered globally

feat(antdv): add AntDesignVueResolverOptions support exclude component

---

src/core/declaration.ts

This fixes the global component declaration file (dts) generating absolute paths on Windows.
Closes #166

fix: declaration generation not detecting absolute paths on Windows

---

src/core/declaration.ts
src/core/utils.ts

fix: component's path should be transformed in dts

---

src/core/resolvers/prime-vue.ts

The tooltip is used as a directive, and it should be registered globally.

fix(prime-vue): remove 'Tooltip' from the component list

---

src/core/resolvers/prime-vue.ts

自动引入primevue时component.d.ts中的文件对组件的指向为.vue文件，导致导入的组件ts类型为any

fixed auto import primevue components without ts support

---

src/core/options.ts

Fix proposition for [#246](https://github.com/antfu/unplugin-vue-components/issues/246)

fix: simply set `resolvedDirs` in case of globs option, close #246

---

src/core/resolvers/prime-vue.ts

Most UI Component libraries use prefix to allow fast distinguish between library and other components, even if PrimeVue doesn't use this practice, with this option we may use prefix for PrimeVue components.
Basically this is equivalent for:
```javascript
function PrimeVuePrefixResolver (options) {
const resolver = PrimeVueResolver(options)
const resolve = resolver.resolve
resolver.resolve = (name) => {
if (options.prefix) {
if (!name.startsWith(options.prefix)) return
return resolve(name.substring(options.prefix.length))
}
}
return resolver
}
```
But I really believe this should be in upstream. Best practice for everyone.

feat(prime-vue): added prefix option

---

src/core/options.ts
src/core/unplugin.ts

Must return the sourcemap to vite, otherwise it would broke the sourcemap when debugging.
There is no default value for dts. It is always false if there is no config. But the document says its default value is `isPackageExists('typescript')`.

fix: source map

---

src/core/resolvers/tdesign.ts

使用 ```unplugin-vue-components``` 动态入组件时，使用
```<t-config-provider></t-config-provider>``` 
会由于 unplugin-vue-components 的原因 导入 es/config-provider/style 而出现404异常
> 这是由于  https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/tdesign.ts 的匹配规则是:  只要以t开头均视为有style的组件，但config-provider未提供style

fix(tdesign): ignore config-provider/style

---

README.md

The ViteComponents variable is not used in the following code, and seems to be an older version of the code, where the Components variable is not imported

docs(readme): fix confusion in readme

---

src/core/transforms/directive/vue2.ts

This causes runtime error:
`[plugin:unplugin-vue-components] Cannot read property 'type' of undefined`

fix: add check for empty args[1]

---

src/core/resolvers/element-ui.ts

This is actually an extension of this modification: https://github.com/antfu/unplugin-vue-components/commit/af8a7a0afd34e15034d9d39fc5622c74aaa9de81#diff-0b83587ef377a4d009821193cbfa7413273d34fddfdafc110049fe72eac51785R74-L24
Currently `ElementUiResolver` accidentally handles components with names like `ElegantComponent` just because their names start with `El`. I've been unable to determine the circumstances under which the commit mentioned above was made, but it appears that `ElementUiResolver` was missed at the time.
As an aside, in the future, perhaps options such as `exclude` will have the ability to be ported to `ElementUiResolver`, but that is not what this PR is intended to discuss.

fix(element-ui): unexpected handling of components

---

src/core/resolvers/headless-ui.ts

Change componentName clearing from prefix value in HeadlessUiResolver. Current Regex is not working at all.

fix(headless-ui): update regex

---

src/core/unplugin.ts
src/types.ts
src/vite.ts

This pull requests adds an `api` to `unplugin-vue-components`, allowing it to be used programmatically.
The benefit of exposing an API is that frameworks can easily integrate with this plugin and leverage any component resolvers that the user has already configured, providing a consistent DX.
[îles](https://iles-docs.netlify.app/) uses this api to [resolve components](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/plugin/wrap.ts#L113-L115) inside islands.
It also can [conditionally inject imports](https://github.com/ElMassimo/iles/blob/main/packages/iles/src/node/plugin/wrap.ts#L79) based on whether the islands are SSR-compatible. This is an advanced use case that wouldn't be possible if the user imported components manually.

feat: add a components api to allow manual detection in frameworks

---

src/core/resolvers/vuetify.ts

added a second resolver under vuetify for the new Vue3/composition-api compatible version of vuetify now in beta, which uses a new import path for components.
After making this, I thought to look at the other resolvers and I didn't see other ones with multiple implementations exported, so I'm thinking the way to do this would be to instead give the resolver an optional parameter to set the version to the v3 beta. I've got that ready in my local version, and am happy to update it to that upon request. 
closes #200

feat(resolver): add Vuetify 3 Beta resolver

---

src/core/resolvers/arco.ts

https://github.com/arco-design/arco-design-vue/issues/864
添加一个类型正确的配置（importStyle可以赋值空字符串绕过，但类型不符合），可以让按需引入组件时，不引入样式文件，以达到不覆盖Arco主题包的目的。这个属性如果不使用将不会对原来的配置有任何影响。

feat(arco): new option sideEffect

---

src/core/resolvers/arco.ts

添加以 slot 方式使用 `a-descriptions-item` 组件支持。
```vue
<a-descriptions title="title">
<a-descriptions-item label="foo">bar</a-descriptions-item>
</a-descriptions>
```
https://github.com/arco-design/arco-design-vue/tree/main/packages/web-vue/components/descriptions
arco 组件库版本 `v2.21.1`（2022-03-25）

fix(arco): add component `DescriptionsItem` support

---

src/core/resolvers/quasar.ts

When using `"type": "module"`, QuasarResolver leads to `require() is not defined` errors.
Because `import()` of JSON files is not supported yet, the solution is to use readFileSync for now (and resolve the path with `local-pkg`).
This might also solve #332

fix(quasar): replace require() by readFileSync() in QuasarResolver

---

src/core/resolvers/vant.ts

VantResolver would make a mistake in generating component name
just like
`VantButton: typeof import('vant/es')['tButton']`
`"vant/es/t-button/style/index"` this file does not exist
maybe that can help
```
if (name.startsWith('Vant')) {
const partialName = name.slice(4);
return {
/*... */
};
}
```

fix: vantResolver partial name

---

src/core/resolvers/vant.ts

I found that I use `<VantButton>` to code. But the 'Vant' is not the correct prefix.
This plugin generated codes like that `VantButton: typeof import('vant/es')['tButton']`.
I'm so sorry for that mistake.
😣

revert: vantResolver partial name

---

examples/vite-vue3/src/components/collapse/collapseFolderAnd/CollapseFolderAndComponentPrefixes.vue
src/core/utils.ts
src/types.ts
test/__snapshots__/search.test.ts.snap
test/search.test.ts

When using `directoryAsNamespace: true` a component path like `src/components/collapse/collapseFolderAnd/CollapseFolderAndComponentPrefixes.vue` would be converted into a component named `CollapseCollapseFolderAndCollapseFolderAndComponentPrefixes`.
I implemented an option to collapse same prefixes in folder names and file name, so that it becomes `CollapseFolderAndComponentPrefixes`.
Closes #307

feat: add `collapseSamePrefixes` option to prevent duplication inside namespaced component name

---

README.md
package.json
pnpm-lock.yaml
src/core/transforms/directive/vue2.ts
src/types.ts

- use `estree-walker`.
`estree-walker` is faster and simpler than `@babel/traverse`.
FYI: [a simple benchmark](https://github.com/sxzz/unplugin-jsx-string/releases/tag/v0.3.0) in my plugin.
~~P.S. Please keep `estree-walker` 2.x, cause `estree-walker@3` is a ESM-only package.~~

perf!: use estree-walker

---

src/core/unplugin.ts

some scenes, `compile.mode` is `development`, but `compiler.watcher` is undefined. For example:
1. `webpack.config.js` set mode `development` but `watch: false`.
2. `plugin` is executed earlier than `new Watching`, that maybe lead file changed but `Watching` have not been instantiated.
3. `compiler.watching` is supported since `webpack@5.0.0-rc.1`
close #436

fix: compiler.watcher undefined

---

src/core/constants.ts
src/core/context.ts
src/core/transforms/directive/index.ts
test/__snapshots__/transform.test.ts.snap
test/transform.test.ts

fix #364 
Use a prefix to seprate directive name from the component
generated dts file will be like 
```ts
import '@vue/runtime-core'
declare module '@vue/runtime-core' {
export interface GlobalComponents {
InfiniteScroll: typeof import('./src/components/InfiniteScroll/index.vue')['default']
'V-InfiniteScroll': typeof import('element-plus/es')['ElInfiniteScroll']
}
}
export {}
```

feat: support component and directive in same name

---

src/core/options.ts

In PR #409 forgot to add `collapseSamePrefixes` option default value, so the editor has TS error:

fix: missing `collapseSamePrefixes` option default value

---

src/core/unplugin.ts

fix #403
fix #419
1. The `options.dts` is unresolved, if the user not setting `dts` then will return `undefined` (not default value `true`), so must be use from the resolved option `ctx.options.dts`.
2. The `ctx.generateDeclaration()` can't resolve the UI components (get from resolvers) on first call on startup dev server, whether UI components in the `components.d.ts` exists or not, will be removed on startup dev server.
This PR changes to generate .d.ts file on startup server if `ctx.options.dts` is true and the file (like `components.d.ts`) exists.
(Of course, `components.d.ts` will still be updated normally when adding, updating files or trigger `transform` hook.)
---
`components.d.ts` (before startup server):
```ts
declare module '@vue/runtime-core' {
export interface …
```

fix: lose components types of components.d.ts

---

examples/vite-vue3/components.d.ts
examples/vite-vue3/vite.config.ts

Fix path in `examples/vite-vue3/components.d.ts` (it is regenerated):
```diff
-   MyCustom: typeof import('./../../../../../src/CustomResolved.vue')['default']
+   MyCustom: typeof import('./src/CustomResolved.vue')['default']
```

chore: fix wrong component path in components.d.ts of example

---

src/core/resolvers/element-plus.ts

Element Plus can contain components without css files. There seems to be only one such component right now, `ElAutoResizer`. Now it comes to an error of loading un-existed styles file.
This PR adds a list of components without styles that can be updated later, and toggles the `importStyle` flag to false for them.
https://github.com/element-plus/element-plus/issues/7933

fix(element-plus): handling components without styles

---

src/core/resolvers/element-plus.ts

With the release of new versions of Element Plus, it is possible that components that do not have their own style files may appear, which causes an error when trying to resolve non-existent style files. Right now, there seems to be only one such component: `ElAutoResizer`. It has been fixed in https://github.com/antfu/unplugin-vue-components/pull/468
At the same time would be handy for getting around such blocking cases quickly without having to wait for a new release of `unplugin-vue-components`.
On the other hand, it seems useful to keep a list of already known components without styles inside the resolver. 
In this PR I suggest combining support for both options.
https://github.com/element-plus/element-plus/issues/7933

feat(element-plus): add noStylesComponents for resolver options

---

README.md
src/core/resolvers/bootstrap-vue.ts

This PR adds support for BootstrapVue component aliases and directives (`options.directives: boolean` - default: `true`). 
The BootstrapVue resolver has also been added to the `README.md` and the list of supported resolvers has been reordered by name. I can revert these changes if I you don't want the `README.md` updates as part of this PR.
FYI @BenediktHeinrichs - I'm curious to know why [you stopped using it](https://git.rwth-aachen.de/coscine/frontend/apps/ui/-/merge_requests/74/diffs?commit_id=c8c53cdd1f120b82a3e78c5417a79863d262d4b7) in the project you mentioned?

feat(bootstrap-vue): add support for aliases and directives

---

src/core/resolvers/tdesign.ts

See #474
#474
I'm not sure this is the best way the solve this problem, I'm first time to work with this plugin.  
Please tell me if there is a better way to solve this.

feat(tdesign): add esm option

---

src/core/transforms/component.ts

In SFC, When using some plugin like plugin-vue-jsx, resolveComponent will be imported as _resolveComponent1 to avoid duplicate import. Change the RegExp `/_resolveComponent\("(.+?)"\)/g ` to `/_resolveComponent[0-9]*\("(.+?)"\)/g` so that the component in jsx can be imported normally.
In fact, when you using a jsx file or runing vite in dev mode, it is also normal, but build mode is not.This may be confusing and cause bug. So I think it's necessary to fix it.

feat: compatible with plugin-vue-jsx

---

src/core/options.ts

When ` "type": "module"`, `require` is not working.

fix: get vue version in esm version

---

src/core/options.ts
src/core/transforms/directive/vue2.ts
test/__snapshots__/transform.test.ts.snap
test/transform.test.ts

In Vue 2.7, `render` is renamed to `_sfc_render`.

fix: directive for vue 2.7

---

src/core/resolvers/bootstrap-vue.ts

BootstrapVue alias for date picker was reversed :
--> https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/src/components/form-datepicker/index.js

fix(bootstrap-vue): dropdown alias

---

src/core/resolvers/tdesign.ts

- add rules for TDesign's new components
- https://github.com/Tencent/tdesign-vue-next/issues/1523

feat(tdesign): add new rules for tdesign

---

README.md

Following the "Usage" section in the docs, I tried to use this plugin and spent like half an hour trying to figure out why it's not working.
At first glance it looked very simple to use. Little I knew that it actually only import components from a specific path set by `dirs` option. Which I had to change according to my project structure.
So I added a little note so new users can have a heads up about the default path.

docs: add note on default import path

---

src/core/resolvers/arco.ts
test/resolvers/arco.test.ts

`Icon` of `ArcoDesign` support config `iconPrefix`, but `ArcoResolver` not supports. 
this PR add the new option to support config `iconPrefix` for `arco`

feat(arco): add iconPrefix option for arco resolver

---

src/core/resolvers/prime-vue.ts

The PrimeVue resolver was missing an entry for row, so the Row component could not be used.
An issue is more work than a PR,, so no linked issue.
Would it make more sense to use the exclusion option by default? Then this needs to be reworked, but the current implementation seems a bit clunky.

fix(prime-vue): add missing row component

---

src/core/resolvers/vueuse-directive.ts

In VueUse, name of directive is not containing `use`-prefix, e.g. `useElementSize` -> `vElementSize` (not `vUseElementSize`).
In this PR, I remove the prefixed `Use` in directive's name in `VueUseDirectiveResolver`, so that we can auto-import these directives properly.

fix(vueuse): remove "use" prefix in directive

---

src/core/resolvers/varlet-ui.ts

`varlet-ui`组件库，组件`ImagePreview`
https://varlet.gitee.io/varlet-ui/#/zh-CN/image-preview
`vite`+`vue3`项目中，`varlet-ui`组件库不能自动导入组件`ImagePreview`
```typescript
// vite.config.ts
import autoImport from 'unplugin-auto-import/vite';
import { VarletUIResolver } from 'unplugin-vue-components/resolvers';
export default defineConfig({
plugins: [
autoImport({
resolvers: [VarletUIResolver({ autoImport: true })],
eslintrc: { enabled: true },
})
]
});
```
可以通过下面配置暂时解决：
```typescript
// vite.config.ts
import autoImport from 'unplugin-auto-import/vite';
import { VarletUIResolver, getResolved } from 'unplugin-vue-components/resolvers';
export default defineConfig({
plugins: [
autoImport({
resolvers: [
VarletUIResolver({ autoImport: true }),
[(name: string) => (name === 'ImagePreview' ? …
```

varlet-ui组件自动导入样式，添加ImagePreview

---

src/core/transforms/component.ts
test/__snapshots__/transform.test.ts.snap
test/transform.test.ts

When use `@vitejs/plugin-vue2-jsx` to transform jsx code, this plugin will not generate tag code in jsx file.
For example: 
```
export default {
render(){
return (
<some-tag/>
)
}
}
```
`@vitejs/plugin-vue2-jsx` will generate this code into 
```
export default {
render(){
return h("some-tag")
}
}
```
unplugin's `resolveVue2` function's [RegExp](https://github.com/antfu/unplugin-vue-components/blob/90b549d0080ed2591edba477187c7171853341e9/src/core/transforms/component.ts#L13)
will not generate `h` function which generated by `@vitejs/plugin-vue2-jsx`.
This PR change the `resolveVue2`'s RegExp to make sure unplugin will read the h function.
This RegExp looks have a problem.
It will match `c` not `_c`. and i don't know how to make the new RegExp match `_c`.but in my project, i test it(`_c` …

feat: compatible with @vitejs/plugin-vue2-jsx

---

src/core/resolvers/tdesign.ts
test/resolvers/tdesign.test.ts

add exclude option.
close #552 
close #505

feat(tdesign): add exclude option

---

src/core/utils.ts

Directory structure:
```
- src
- components
- dir-a
- index.vue
- dir-b
- index.vue
```
Configs:
```ts
{
plugins: [
Components({
allowOverrides: true,
dts: 'src/components.d.ts',
globs: ['src/components/**/index.vue']
}),
]
}
```
When use `globs` option, `resolvedDirs` will always empty, and `folders` will also empty
https://github.com/antfu/unplugin-vue-components/blob/0c9131cd8f34d50f9d9b885b54ead6ae36657d53/src/core/options.ts#L33-L38
https://github.com/antfu/unplugin-vue-components/blob/0c9131cd8f34d50f9d9b885b54ead6ae36657d53/src/core/utils.ts#L120-L135

fix: use `globs` option cannot resolve index.vue

---

.vscode/settings.json
README.md
examples/vite-vue3/src/components/collapse/collapseFolder/CollapseFolderAndComponentFromRoot.vue
examples/vite-vue3/src/components/collapse/collapseFolder/FolderAndComponentPartially.vue
examples/vite-vue3/src/components/collapse/collapseFolderAnd/CollapseFolderAndComponentPrefixes.vue
src/core/utils.ts
src/types.ts
test/__snapshots__/search.test.ts.snap

The previous implementation only compared prefixes of files/folders with all previous names at once.
Now, the algorithm walks incrementally from the previous folder name to try to find a prefix match.
Prefix matcher implementation:
```
Previous:
A/B/C/X -> X.startsWith("ABC")?
New:
A/B/C/X -> X.startsWith("C"), X.startsWith("BC"), X.startsWith("ABC)?
```
Also updated and added missing docs in README.
Fixes #546 
The algorithm is now O(n^2) but folder depths of components are not as deep as to cause trouble (hopefully).

fix(collapseSamePrefixes): missing collapse when prefix did not match from beginning

---

package.json
pnpm-lock.yaml
src/nuxt.ts

This PR make `unplugin-vue-components` compaible with the new `nuxt@3.0.0` release, this is needed until Nuxt supports using resolvers from this plugin, in order to use e.g. `ElementPlusResolver` in Nuxt projects.
https://github.com/nuxt/framework/issues/487

feat: support nuxt@3.0.0

---

src/core/resolvers/varlet-ui.ts

feat(varlet-ui): support hover directive

---

package.json
pnpm-lock.yaml

Removes hard dependency on @nuxt/kit, changing it to an optional peer dependency so that non-nuxt projects aren't forced to take on 100+ additional dependencies in order to use this package.
Fixes #606

fix: remove hard dependency on nuxt, close #606

---

src/core/resolvers/tdesign.ts

Tdesign no need import sideEffects. When import tdesign, it will import all css. So now it needn't import sideEffect

feat: tdesign no need import sideEffects

---

src/core/resolvers/ionic.ts

strict checking on Ionic components, better Ionic v7 support (excluding e.g. IonSlider, IonSlide and etc )
Based on https://github.com/nuxt-modules/ionic/blob/main/src/imports.ts by @danielroe
-
-

refactor: ionic resolver strict components 

---

examples/vite-vue3/package.json
examples/vite-vue3/vite.config.ts

problem: .The problem just belongs to examples/vite-vue3. There is no component in web page after running 'pnpm build' and 'pnpm preview'
process: After running 'pnpm build', the path '...ComponentA.vue' will become '...ComponentA.vue?vue&type=script&setup=true&lang.ts'. But vite config option 'include' do not include this situation. So I think it's time to change 'include' option's regex. The soluation case is the same as 'core/unplugin.ts'.
#503 
Although I soluation the probleam, I don't know the process that the path '...ComponentA.vue' will become '...ComponentA.vue?vue&type=script&setup=true&lang.ts'.

fix(vite-vue3): update include regex to support production build

---

src/core/context.ts
src/core/utils.ts

This PR renames `normalizeComponetInfo` to `normalizeComponentInfo`, it's just a typo.
[I searched github](https://github.com/search?q=normalizeComponetInfo&type=code) to find if someone imports normalizeComponetInfo, but didn't find any open sourced project, exept of forks of this project. So, I suppose, this won't affect anyone.

fix: typo in `normalizeComponentInfo` method name

---

examples/vite-vue3/src/components/kebab-case/KebabCaseFile.vue
examples/vite-vue3/src/components/kebab-case/kebab-case-collapse/KebabCaseCollapseFile.vue
src/core/utils.ts
test/__snapshots__/search.test.ts.snap

`collapseSamePrefixes` should directly count the PascalCased name's length instead of kebab-cased one.
fixes #738

fix(utils): collapse prefixes in PascalCase name

---

src/core/resolvers/varlet-ui.ts

support `styleExtname` option for fully specified path.

feat(varlet-ui): support `styleExtname` option

---

README.md

match file to exclude in components.d.ts was fixed by https://github.com/unplugin/unplugin-vue-components/pull/645
but i can't find any explanation in docs, this PR just to replenish it
- resolve https://github.com/unplugin/unplugin-vue-components/issues/751
- resolve https://github.com/unplugin/unplugin-vue-components/issues/617
- resolve https://github.com/unplugin/unplugin-vue-components/issues/748
- resolve https://github.com/unplugin/unplugin-vue-components/issues/420

docs: additional notes on `globs` and `exclude`

---

src/core/options.ts

If it's a directory, append a trailing slash at the end.https://github.com/unjs/mlly/issues/158#issuecomment-1468867050
fixed #767

fix: get wrong vue version in monorepo

---

src/core/options.ts
src/types.ts
test/search.test.ts
vitest.config.ts

Context:
- https://github.com/slidevjs/slidev/issues/2066
- https://github.com/unplugin/unplugin-vue-components/commit/8e1f72ef65f4ba1e4066cc1889d9fc053e3c45c6
- https://github.com/unplugin/unplugin-vue-components/actions/runs/13406033622/job/37446016716

fix: fix how globs resolves, excludes nested `node_modules` folder by default

---

README.md
src/core/unplugin.ts

When using vue-loader experimentalInlineMatchResource, the request will have an additional .js/.ts extension to match the js/ts module rule
```diff
// without experimentalInlineMatchResource
- src/App.vue?vue&type=script&setup=true&lang=ts
// with experimentalInlineMatchResource
+ src/App.vue.ts?vue&type=script&setup=true&lang=ts
```
But the default include RegExps failed to match the request

fix: compatible with vue-loader experimentalInlineMatchResource

---

.gitignore
examples/vite-vue2/vite.config.ts
examples/vite-vue3/vite.config.ts
src/core/context.ts
src/core/declaration.ts
src/core/unplugin.ts
src/types.ts

This PR will add a `dumpUnimportComponents` option to export information about all components.
I recently created an [eslint-plugin-unimport-components](https://github.com/ilyaliao/eslint-plugin-unimport-components) tool to automatically complete imports, inspired by [eslint-plugin-unimport](https://github.com/antfu/eslint-plugin-unimport). I hope to collaborate with `unplugin-vue-components` to obtain information about all components, allowing ESLint to automatically import components.
(Automatically Generated Components JSON File)
(Eslint Error Message)

feat: introduce `dumpComponentsInfo` option

---

src/core/declaration.ts
test/__snapshots__/dts.test.ts.snap
test/dts.test.ts

Vue Language Tools uses `GlobalDirectives` to provide type support for global directives. `ComponentCustomProperties` causes directives incorrectly appear in the component's properties.

feat: use `GlobalDirectives` instead of `ComponentCustomProperties`

---

README.md

Now, webpack/vue-cli require without `.default`.
https://github.com/unplugin/unplugin-vue-components/blob/d542b307888b242566a5b00e1ee1c5b8dc8a916f/examples/vue-cli-vue3/vue.config.js#L2

docs: update vue-cli/webpack/rspack require usage

---

examples/vite-vue2/package.json
examples/vue-cli/package.json
examples/vue-cli/vue.config.js
pnpm-lock.yaml

This PR fixes Vue 2 example project runtime issues by updating `vue.config.js` and pinning Vue to `2.7.16`.

fix: vue2 example project runtime errors

---

src/core/context.ts
src/core/declaration.ts
test/__snapshots__/transform.test.ts.snap
test/transform.test.ts

The `prefix` option from #850 was only applied to type declarations, which caused a resolution failure during the transform stage. 
This PR corrects the behavior by applying the prefix to the internal `componentNameMap` and adds tests to prevent regressions.

fix: correct prefixed component name

---

src/core/resolvers/tdesign.ts

Fix TDesign "QRCode" component cannot be imported due to case sensitivity.
Modify the export to be "QRCode" instead of "Qrcode".
Code reference: https://github.com/Tencent/tdesign-vue-next/blob/develop/packages/auto-import-resolver/src/resolver.ts

fix(tdesign): add QRCode component support
